config/routes.rb
Rails.application.routes.draw do
  resources :states, only: [] do
    # /states/:state_id/counties
    resources :counties, only: :index do
      resources :cities, only: :index
    end
  end

  resources :accounts
  root to: 'accounts#index'
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :city
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :county, optional: true
  has_many :accounts

  scope :name_asc, -> { order(name: :asc) }
  scope :select_collection, -> { name_asc.map { |s| [s.name, s.id] } }
end

app/models/county.rb
class County < ApplicationRecord
  belongs_to :state
  has_many :cities

  scope :name_asc, -> { order(name: :asc) }
  scope :select_collection, -> { name_asc.map { |s| [s.name, s.id, { url: Rails.application.routes.url_helpers.state_county_cities_path(state_id: s.state_id, county_id: s.id) }] } }
end

app/models/state.rb
class State < ApplicationRecord
	has_many :counties

	scope :name_asc, -> { order(name: :asc) }
  scope :select_collection, -> { name_asc.map { |s| [s.name, s.id, { url: Rails.application.routes.url_helpers.state_counties_path(s) }] } }
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:name, :city_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    state = State.find(params[:state_id])
    county = state.counties.find(params[:county_id])
    cities = county.cities
    render json: cities.select_collection
  end
end

app/controllers/counties_controller.rb
class CountiesController < ApplicationController
  def index
    state = State.find(params[:state_id])
    counties = state.counties
    render json: counties.select_collection
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div data-controller='city-selector'>
    <%= form.label :state_id %>
    <%= form.select :state_id,
                    State.select_collection,
                    { include_blank: true },
                    {
                      class: 'form-control',
                      data: {
                        target: 'city-selector.state_input',
                        action: 'city-selector#state_changed'
                      }
                    }
    %>

    <%= form.label :county_id %>
    <%= form.select :county_id, [], {}, { 
                    class: 'form-control',
                    data: {
                      target: 'city-selector.county_input',
                      action: 'city-selector#county_changed'
                    }                                          
                  } %>

    <%= form.label :city_id %>
    <%= form.select :city_id, [], {}, { class: 'form-control', 
                    data: {
                      target: 'city-selector.city_input',
                      city_id: account&.city_id,
                      county_id: account&.city&.county_id,
                      state_id: account&.city&.county&.state_id
                    } } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.name %></td>
        <td><%= account.city_id %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @account.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @account.city_id %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Template2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>